export const CREATE_APARTMENT = 'CREATE_APARTMENT';
export const READ_APARTMENT = 'READ_APARTMENT';
export const READ_APARTMENTS = 'READ_APARTMENTS';
export const UPDATE_APARTMENT = 'UPDATE_APARTMENT';
export const DELETE_APARTMENT = 'DELETE_APARTMENT';
